### ISSUE TITLE
Move project yaml files into a different folder

### ISSUE THREAD

**Issue by OscarAblinger** [awesome-global-contributions/awesome-global-contributions#16]
Leaving them in `/src` just forces us to ignore other files when processing them and either turning them into the markdown file or query them for the website.
Currently it's only `TEMPLATE.yaml` and `ENTRY_REQUIREMENTS.md`, but I could see a future, where more files would fit in that folder.

How about if we move them into `/projects` or `/src/projects`?

**Comment by AdrienLemaire** [comment]
another option is to move the template/reqs files to the root of the repo, or to a `docs/` directory.
`src` stands for "source", so leaving these two files only in that directory doesn't make much sense.
I'm fine with renaming `src` to `projects`. I don't think filtering out unrelated files is a big deal, especially after I write a script to auto-generate a `dist/projects.json` file or something.
So, I leave it up to you :)

**Comment by OscarAblinger** [comment]
I was not aware that you planned to actually create a `projects.json`. In that case, we at least don't have to keep the blacklist in-sync across two projects.

It'd still somehow hide the `TEMPLATE.yaml` and also the `ENTRY_REQUIREMENTS.md` once we have a decent amount of projects.
And we'd have a mixing of concerns.

I think I'll move the two other files to the root for now and and leave the projects in `src` (see PR #18).
