### ISSUE TITLE
Github Actions: auto-update Readme

### ISSUE THREAD

**Issue by AdrienLemaire** [awesome-global-contributions/awesome-global-contributions#27]
Due: 2019/08/31 #7 

Running the script for each PR increases risk of git conflicts and makes reviews tedious.

We want to have the Github CI update the README automatically for us when merging a PR containing a new project yaml file.

Todo:
- [x] Add action
- [x] Action must install yq & python3, exec the `./bin/yaml2markdown.sh` script, git add, git commit and git push
- [x] Check if the commit is done in the branch or master
- [x] Verify it in a PR
- [x] Update `CONTRIBUTING.md` to reflect simplified procedure

**Comment by OscarAblinger** [comment]
I assume the `yaml2json.sh` should also be executed in this way?

**Comment by AdrienLemaire** [comment]
@AblingerOscar well, it's already executed by yaml2markdown.sh :)
https://github.com/awesome-global-contributions/awesome-global-contributions/blob/master/bin/yaml2markdown.sh#L18

**Comment by OscarAblinger** [comment]
It seems the current action on the PR doesn't really work if it happens from forks :/

The reason for it I randomly found [in this issue](https://github.com/stefanzweifel/git-auto-commit-action/issues/25)

It seems that we'd have to do it after merging and reading through your initial issue, it seems like that is what you suggested ^^'

**Comment by OscarAblinger** [comment]
The autogenerating script does not seem to work correctly in action-yq :/
I'll try to set up the same docker environment locally and try it there a bit.
I's a bit cumbersome to edit github actions.

**Comment by OscarAblinger** [comment]
Currently the script pushes directly to the master without creating another PR (since I think that would just clutter it too much)
Would you prefer if it would create a PR @AdrienLemaire ?

**Comment by AdrienLemaire** [comment]
@AblingerOscar I think it's great if it updates master directly after a PR is merged. The goal was to simplify reviews :)

**Comment by OscarAblinger** [comment]
I think we can close this even with #62, right?
