### ISSUE TITLE
Discuss about a rename of the repository?

### ISSUE THREAD

**Issue by OscarAblinger** [awesome-global-contributions/awesome-global-contributions#4]
The name of the repository will often be the first thing people read: On an awesome-awesome list, in searches or in posts.
I, personally, do not think that two abbreviations make for an easy and memorable name – especially since "SDG" is not common on github.

While SDG are definitely a good reference, I would only start mentioning it in the long description.

Some possible alternatives:
- awesome-impact
- awesome-social-impact
- awesome-for-good
- awesome-global-challenges
- awesome-global-impact

**Comment by AdrienLemaire** [comment]
Alright. You had already suggested names like `awesome-impact`, but after listing a bunch of loosely related collections [in the readme](https://github.com/Fandekasp/awesome-oss-sdgs/#awesome-oss-sdgs--), I found other lists which names can easily be confused with ours (although the content differs a bit). Please have a look at the Readme, here are some of the most controversial ones:

- [awesome-social-impact](https://github.com/OtavioRMachado/awesome-social-impact)
- [awesome-techforgood](https://github.com/TechforgoodCAST/awesome-techforgood)
- [awesome-human-tech](https://github.com/humanetech-community/awesome-humane-tech#readme)
- [awesome-open-source-supporters](https://github.com/zachflower/awesome-open-source-supporters#readme)
- [awesome-oss](https://github.com/hzoo/awesome-oss)
- [awesome-foss-apps](https://github.com/DataDaoDe/awesome-foss-apps#readme)

Notice how one of your suggestions actually already exists: "awesome-social-impact".

I suppose this issue depends on #5.

**Comment by OscarAblinger** [comment]
I've read the similar projects in the readme and even took inspiration from them for this list.
I didn't really think about people confusing them with this repository, though. That's a valid concern 🤔
I guess it depends on how big and maintained that project is and of course on #5 as you've mentioned.

**Comment by AdrienLemaire** [comment]
@AblingerOscar how about we adopt your proposition **awesome-global-challenges**?

This is probably fine for a list of related OSS projects.
Users of awesome lists in general are our target.

This will also open doors in the future to do more than this, like studying about global issues, doing papers meta-analysis etc.

**Comment by AdrienLemaire** [comment]
If you agree on the name, how about we create a github organization by that name, and a slack channel (slack threads are probably more useful to discuss fine points and details than github issues)?

**Comment by AdrienLemaire** [comment]
Thinking about it, maybe **awesome-global-issues** better fits the bill. What do you think?

**Comment by OscarAblinger** [comment]
I like **awesome-global-issues**.
I need to point out the irony of the name though: To someone not familiar it, it seems to list _awesome issues_, instead of solutions to those. (**awesome-global-challenges** has similar connotations, now that I look at it)
Should we try to get something like "projects" or "contributions" into the name?
Something like **awesome-global-projects** or **awesome-social-os-projects**. It doesn't sound that good, though, sadly 🤔 

> If you agree on the name, how about we create a github organization by that name, and a slack channel?

Good idea :)
Can you actually migrate projects to an organization or would these issues be lost?

**Comment by AdrienLemaire** [comment]
What about **awesome-global-issues-contribution**?
Name is a tad long, but I've seen worse in awesome lists.

I can't explain why, but something about "social" doesn't sound right to me. The LF Energy goal to reform the Grid is directly connected to solving the global warming issue, but I don't see the social aspect in it.

Definition:

1. relating to society or its organization. "alcoholism is recognized as a major social problem"
2. an informal social gathering, especially one organized by the members of a particular club or group. "a church social"

> seeking or enjoying the companionship of others; friendly; sociable; gregarious. ... living or disposed to live in companionship with others or in a community, rather than in isolation: People are social beings.

Well, I'm not English native, so if you believe it suits nicely, let's go for it.

**Comment by AdrienLemaire** [comment]
> Can you actually migrate projects to an organization or would these issues be lost?

Yes we can

> Transfer ownership
> Transfer this repository to another user or to an organization where you have the ability to create repositories.

**Comment by OscarAblinger** [comment]
> What about awesome-global-issues-contribution?

Not bad. But I agree it's a bit long, but that shouldn't be a problem.
We could shorten it to **awesome-global-contribution(s)**.

> I can't explain why, but something about "social" doesn't sound right to me.

Yeah, social is more just a part of the things we want to cover and not all of them, so it's not fitting super well.
I think I liked **awesome-global-projects** better anyways.

> Well, I'm not English native, so if you believe it suits nicely, let's go for it.

Neither am I ^^

**Comment by AdrienLemaire** [comment]
Alright, awesome-global-contributions it is! Thank you
