### ISSUE TITLE
Define what qualifies a project for this repository

### ISSUE THREAD

**Issue by OscarAblinger** [awesome-global-contributions/awesome-global-contributions#5]
Related: #2
We should make a clear guide on what projects qualify for this list.

Some questions I came up with, that should be answered:
- Do they need to be FOSS? Does the end product need to be free? Must the organisation be a non-profit?
- Is any license okay?
- Do they need to have proper contribution guides? What qualifies a good contribution guide?
- Do they need to be global? Is it okay if they focus only on a specific third world country? Is the same okay for a first world country?
- Do they need to use a SDG label themselves?
- Does the software project need to be the primary focus of the organization/initiative? Does e.g. a website for a non-profit, SDG-related organization count? Does it count, if the focus of that website is to coordinate their efforts? What if it's for coordinated efforts with independend volunteers?
- Do pure research projects counts?

**Comment by AdrienLemaire** [comment]
Those are indeed important questions.

First, let's agree on the target user for this list. The target I had in mind is **the IT folk who wants to altruistically contribute to a highly impactful project**. 
If we agree on this definition, this should already dramatically reduce the number of candidate projects.

> Do they need to be FOSS? Does the end product need to be free? Must the organisation be a non-profit?

Following this line of thought, I wouldn't want to participate in a for-profit project. It would have to be the end of the world and the only solution remaining... but maybe you can find a counter-argument?
⇒ I'd like the organization to be non-profit, but the project doesn't have to. Adding the information to the list would be useful though (:free:)

> Is any license okay?

Licensing isn't my cup of tea, and I'm wondering how many IT folks are well-versed in the subtilities of various OSS licenses. Thus, I wouldn't worry too much about it, and if you do care about it, that's fine.

> Do they need to use a SDG label themselves?

I suppose it's our job to evaluate whether a project has an impact on an SDG or not. That's kind of our unique value proposition.

> Does the software project need to be the primary focus of the organization/initiative? Does e.g. a website for a non-profit, SDG-related organization count? Does it count, if the focus of that website is to coordinate their efforts? What if it's for coordinated efforts with independent volunteers?
> Do pure research projects counts?

Maybe it's difficult to set a rule in stone, we'll probably need to discuss unique cases, or rely on the maintainer's good judgment. As long as it meets our target user's expectations, it should be fine.

> Do they need to be global? Is it okay if they focus only on a specific third world country? Is the same okay for a first world country?

As long as they make an SDG actionable, isn't it fine? That's probably a piece of good information to display in the list format.

> Do they need to have proper contribution guides? What qualifies a good contribution guide?

I'm struggling with this. Here's is an example that I'd like to discuss: [**LF Energy**](https://www.lfenergy.org/projects/).

As a project, it looks like one of the best initiative out there for [SDG 7](https://www.undp.org/content/undp/en/home/sustainable-development-goals/goal-7-affordable-and-clean-energy.html) and [SDG 13](https://www.undp.org/content/undp/en/home/sustainable-development-goals/goal-13-climate-action.html). It short, they want to apply the design principles of the internet to The Grid (right now, each country/company manages its infra, few standards, and each grid is loosely connected). Their target is to reduce CO2 emissions from the grid worldwide by 95%. The mission is to connect the power engineer community with the software engineer community to join the best of both worlds.

But the current situation is a real mess. From what I understand, it's currently just a gathering of big-name companies (like the french RTE from EDF) who open-sourced their code. They are poorly organized, very few documentation and no contribution guide. It is very unfriendly to lone developers who wish to help in some way, especially software engineers who don't know about power grid stuff.

Maybe a solution would be listing the LF energy project with a bad grade for beginner-friendliness.
Maybe we can manage an Index, with a score determined by the project's potential impact and it's contribution guide's friendliness?

**Comment by OscarAblinger** [comment]
> The target I had in mind is the IT folk who wants to altruistically contribute to a highly impactful project.

Sounds good, although I would probably closer define which projects.
I'd call Linux a highly impactful project for instance, but the impact isn't related to any SDG.
How about:

> IT folk (programmers, sysadmins, designers), who wants to altruistically contribute to highly socially impactful projects.

I'm still not happy with it, but I've had problems summarizing the idea of this list into words, anyways. I feel like your reddit post does do that rather well though ^^

> Following this line of thought, I wouldn't want to participate in a for-profit project. It would have to be the end of the world and the only solution remaining... but maybe you can find a counter-argument?
> ⇒ I'd like the organization to be non-profit, but the project doesn't have to. Adding the information to the list would be useful though (🆓)

If we choose to include for-profits then I would definitely have a label for those to make it clear.
My argument for allowing for-profit organization's projects is related to big companies supporting non-profit causes. Google and Microsoft for instance have been credited a few times for supporting one of their engineers with an SDG project (though I don't think they are considered the organization behind those projects).
Personally, I'd see it the other way around: The project should not have the goal to make money, but if a for-profit company backs it, I'd see no problem in it, even if they officially own it. I would support a warning for those projects, though. It might just be to improve their image, but some probably use the developed technologies for their own profit, which I, personally, don't like, but can see other people not minding.

> Licensing isn't my cup of tea, and I'm wondering how many IT folks are well-versed in the subtilities of various OSS licenses. Thus, I wouldn't worry too much about it, and if you do care about it, that's fine.

I don't really care too much about them either, just wanted to mention it.

> As long as they make an SDG actionable, isn't it fine? That's probably a piece of good information to display in the list format.

I would agree that the scope shouldn't disqualify a project for this list. However, keep in mind that local projects might be in different languages. That would probably warrant it's own metric/warning label (non-english). Also, it is probably an important decision metric for people seeking to contribute.

> Maybe a solution would be listing the LF energy project with a bad grade for beginner-friendliness.
Maybe we can manage an Index, with a score determined by the project's potential impact and it's contribution guide's friendliness?

That's a great idea, I would definitely do that. A simple score shouldn't be too much work for the initial adding and updating it on request or maybe twice a year should be fine, too. Of course that depends on how complicated the rating should be.

I do like a simple 1-5 stars metric, but I could see a good reason for 1-10 (1️⃣ - 🔟). If you want to go with a more complicated one, we should probably try to look for an already existing metric for that. Closest to that, that I found is the [CHAOSS project](https://github.com/chaoss/metrics#full-list-of-activity-metrics), but that doesn't have a simple formular, seems to be overkill to me and rather hard to maintain.
Personally I'd go with 1-5 or 1-10 depending on how many metrics we will consider. I guess that warrants another issue?

**Comment by AdrienLemaire** [comment]
I thought Linux could be listed for SDG 9 (Industry, Innovation & infrastructure), but you're right, it's a bit of a stretch...

I agree with the other points as well. Let's start with an easy to compute metric for now, and we can always change the algorithm later on when the project is more mature. I didn't know about CHAOSS, thanks for sharing!

**Comment by AdrienLemaire** [comment]
SDGs are about more than global challenges as described on `Wikipedia,` so it's maybe best to not use them as categories. Maybe as labels would be enough?

See #6 for links to other alternatives for classifying global issues.

It's probably easier to first agree on a YAML template (#3) and leaving it to our common sense to define what projects go where. 
We can later on do some screening to improve the quality of the curated list and eventually dress stricter rules.

How about we renaming this issue into "Define what categories should represent global issues"?

**Comment by OscarAblinger** [comment]
> It's probably easier to first agree on a YAML template (#3) and leaving it to our common sense to define what projects go where.

> How about we renaming this issue into "Define what categories should represent global issues"?

I think, for now, going with the SDGs paired with common sense seems to make the most sense to me. We can open a new issue for it, when needed.

Furthermore, I think we've defined a pretty nice outline for what qualifies as a project.
I might write something up on it tomorrow. For now, I'd close the issue, but feel free to re-open it, if you want to discuss further.
