### ISSUE TITLE
Define the target audience of this list

### ISSUE THREAD

**Issue by AdrienLemaire** [awesome-global-contributions/awesome-global-contributions#6]
Related: #5

Suggestions:
1. ~the IT folk who wants to altruistically contribute to a highly impactful project.~ (must be related to sdgs)
2. IT folk (programmers, sysadmins, designers), who wants to altruistically contribute to highly socially impactful projects.
3. The software engineer who wants to volunteer to solve a global challenge.

**Comment by AdrienLemaire** [comment]
Actually, we do not have to use the SDGs for classification.
* SDGs have 17 categories.
* The millennium projects lists [15 global challenges](http://www.millennium-project.org/15-global-challenges/)
* WUN focuses on [4 global challenges](https://wun.ac.uk/wun/globalchallenges)
* 80000 hours researches high-impact career opportunities and has [interesting topics](https://80000hours.org/topics/)
* The Global Challenges Foundation also releases [interesting surveys ](https://globalchallenges.org/en/our-work/risk-survey/attitudes-to-global-risk-and-global-governance-2018)that could inspire us

I think I need to study a bit more about all this now ...

**Comment by AdrienLemaire** [comment]
Definition [global issue](https://en.wikipedia.org/wiki/Global_issue)

> a global issue is any issue that adversely affects the global community and environment, such as environmental issues, political crisis, social issues and economic crisis. Global issues range in severity from minor issues that affect everyone to global catastrophic risks that threaten the existence of the entire human race or its society.
Solutions to global issues generally require cooperation among nations

Wikipedia lists 5 categories:
* World overpopulation
* Overconsumption
* Global warming 
* Human impact on the environment
* Conflict-related

The wiki page [List of global issues](https://en.wikipedia.org/wiki/List_of_global_issues) has 7 global catastrophic risks (and the related [Global catastrophic risk](https://en.wikipedia.org/wiki/Global_catastrophic_risk) page lists 10 anthropogenic potential sources of risk [lol: 19% overall probability for human extinction before 2100]).

Hmmm... the links quickly go to doom's day articles. We'll need to try our best to stay objectives and optimists here :)

**Comment by AdrienLemaire** [comment]
Closing since this issue overlaps with #4 and #5. 
Our target audience is the people using awesome lists, which I believe is mostly the software engineering community.

**Comment by OscarAblinger** [comment]
The links of the different categories are interesting.
Once I find some time for it, I'll look into it a bit farther, too.
But I do think that the SDGs are a pretty good fit.

> Wikipedia lists 5 categories:

I don't think those fit our purposes well, though :/

> lol: 19% overall probability for human extinction before 2100

O.o

> We'll need to try our best to stay objectives and optimists here :)

Yeah, we should definitely have a positive atmosphere for this project ^^
