### ISSUE TITLE
Yaml2Markdown converter

### ISSUE THREAD

**Issue by AdrienLemaire** [awesome-global-contributions/awesome-global-contributions#8]
Due: 08/31 #7 

Using jq/yq, combine all project YAML files and generate markdown output to update the README.md

**Comment by OscarAblinger** [comment]
Do you plan in allowing markdown in the description or name of the projects?
I think that it would be useful for the description, but not necessary for project names

**Comment by AdrienLemaire** [comment]
Allowing markdown in the description is a good idea :+1:

**Comment by AdrienLemaire** [comment]
Getting started on this one.
Need a refresher on jq
https://github.com/fiatjaf/awesome-jq
